service: private-geo-proxy

frameworkVersion: '3'

configValidationMode: error

provider:
  name: aws
  runtime: python3.8

  stage: dev
  region: eu-south-1

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - iam:PassRole
            - logs:CreateLogStream
            - logs:CreateLogGroup
            - logs:PutLogEvents
            - ec2:DescribeInstances
            - ec2:StartInstances
            - ec2:DescribeLaunchTemplates
            - ec2:GetLaunchTemplateData
            - ec2:DescribeLaunchTemplateVersions
            - ec2:RunInstances
            - ec2:CreateTags
            - ec2:TerminateInstances
          Resource: "*"

package:
  patterns:
    - 'lambdas/**'
    - '!venv/**'

functions:
  launch_proxy_ec2:
    handler: lambdas.launch_proxy_ec2.lambda_handler.lambda_handler
    name: ${sls:stage}-launch-proxy-ec2
    description: Launches an EC2 instance to be used as SOCKS proxy
  terminate_proxy_ec2:
    handler: lambdas.terminate_proxy_ec2.lambda_handler.lambda_handler
    name: ${sls:stage}-terminate-proxy-ec2
    description: Terminates the EC2 instance used as SOCKS proxy
  check_proxy_ec2:
    handler: lambdas.check_proxy_ec2.lambda_handler.lambda_handler
    name: ${sls:stage}-check-proxy-ec2
    description: Reports on the status of the EC2 instance used as SOCKS proxy
