name: Continuous Deployment

on:
#  push:
#    branches:
#      - 'main'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    env:
      SLS_VERSION: 2.62.0
    steps:
      - name: Checkout target branch
        uses: actions/checkout@v2.3.3

      - name: Install serverless
        run: curl -o- -L https://slss.io/install | VERSION=${SLS_VERSION} bash
